name: push

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test lint, build

    runs-on: ubuntu-latest

    steps:
      - name: Linux checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run Lint
        run: yarn lint

      - name: Run Build
        run: yarn build
